# Generated by Django 6.0.5 on 2026-06-02 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClientMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id_url", models.URLField(max_length=2048, unique=True)),
                ("client_name", models.CharField(max_length=255)),
                ("client_uri", models.URLField(blank=True, max_length=2048)),
                ("logo_uri", models.URLField(blank=True, max_length=2048)),
                ("redirect_uris", models.JSONField(default=list)),
                ("grant_types", models.JSONField(default=list)),
                ("response_types", models.JSONField(default=list)),
                (
                    "token_endpoint_auth_method",
                    models.CharField(default="none", max_length=64),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("fetched_at", models.DateTimeField()),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cimd_metadata",
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth client metadata",
                "verbose_name_plural": "OAuth client metadata",
            },
        ),
    ]
