# Generated by Django 6.1 on 2026-09-28 11:24
from django.db import migrations


def migrate_cimd_applications(apps, schema_editor):
    OAuthClientMetadata = apps.get_model("oauth_integrations", "OAuthClientMetadata")
    OAuthApplicationMetadata = apps.get_model("oauth_integrations", "OAuthApplicationMetadata")

    for cimd_meta in OAuthClientMetadata.objects.select_related("application").all():
        app = cimd_meta.application
        if not app:
            continue

        if app.client_id.startswith("cimd:"):
            app.client_id = cimd_meta.client_id_url
            app.name = cimd_meta.client_name
            app.save(update_fields=["client_id", "name"])

        if cimd_meta.logo_uri:
            app_meta, _created = OAuthApplicationMetadata.objects.get_or_create(application=app)
            if not app_meta.logo_uri:
                app_meta.logo_uri = cimd_meta.logo_uri
                app_meta.save(update_fields=["logo_uri"])


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_integrations', '0002_oauthapplicationmetadata'),
    ]

    operations = [
        migrations.RunPython(migrate_cimd_applications, migrations.RunPython.noop),
    ]
