# Generated by Django 5.2.7 on 2025-12-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notify_bug_reported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_marketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_quiz_shared',
            field=models.BooleanField(default=True),
        ),
    ]
