# Generated by Django 5.1.4 on 2025-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_rename_initial_repetitions_usersettings_initial_reoccurrences_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="overriden_photo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
