# Generated by Django 6.0 on 2026-01-20 13:54
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersettings_notify_bug_reported_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, default=lambda: f"{uuid.uuid4()}@fake.com"),
        ),
    ]
