# Generated by Django 6.0.1 on 2026-01-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings_notify_bug_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='max_question_repetitions',
            field=models.PositiveIntegerField(default=3, help_text='Maksymalna liczba powtórzeń tego samego pytania w jednej sesji'),
        ),
    ]
