# Generated by Django 6.0 on 2026-01-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersettings_notify_bug_reported_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="student_number",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
