# Generated by Django 5.2.7 on 2026-01-26 21:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='max_question_reoccurrences',
            field=models.PositiveIntegerField(default=3, help_text='Maksymalna liczba powtórzeń tego samego pytania w jednej sesji'),
        ),
    ]
