# Generated by Django 6.0.1 on 2026-01-30 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="max_question_reoccurrences",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Maksymalna liczba powtórzeń tego samego pytania w jednej sesji",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="initial_reoccurrences",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
