# Generated by Django 5.1.6 on 2025-03-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emaillogintoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_profile",
            field=models.BooleanField(
                default=False,
                help_text="Hide profile from other users in search and leaderboards, user will still be able to be added by student_number",
            ),
        ),
    ]
