# Generated by Django 6.0 on 2026-02-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usersettings_max_question_reoccurrences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ban_reason",
            field=models.TextField(
                blank=True, help_text="Reason for the ban", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_banned",
            field=models.BooleanField(
                default=False, help_text="Whether the user is banned from the platform"
            ),
        ),
    ]
