# Generated by Django 6.0.2 on 2026-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_user_ban_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("guest", "Guest"),
                    ("email", "Email"),
                    ("student", "Confirmed Student"),
                    ("lecturer", "Lecturer"),
                ],
                default="email",
                help_text="Determines the user's account type and associated permissions",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
