# Generated by Django 5.1.6 on 2025-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_hide_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usos_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
