# Generated by Django 5.1.6 on 2025-04-29 18:21

from django.db import migrations


def populate_usos_id(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.student_number:
            user.usos_id = user.id
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_usos_id"),
    ]

    operations = [
        migrations.RunPython(populate_usos_id, migrations.RunPython.noop),
    ]
