# Generated by Django 6.0 on 2026-03-08 15:19

from django.db import migrations


def set_student_account_type(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(student_number__isnull=False).exclude(student_number="").exclude(account_type="student").update(
        account_type="student"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_account_type_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(set_student_account_type, reverse_code=migrations.RunPython.noop),
    ]
