# Generated by Django 6.0.2 on 2026-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_root_folder'),
        ('users', '0007_auto_20260308_1619'),
    ]

    operations = [
    ]
