# Generated by Django 6.0 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20260308_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_level",
            field=models.CharField(
                choices=[("basic", "Basic"), ("gold", "Gold")],
                default="basic",
                help_text="Represents the user's account level tier",
                max_length=10,
            ),
        ),
    ]
