# Generated by Django 6.0.2 on 2026-03-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0006_user_root_folder_0007_auto_20260308_1619'),
        ('users', '0008_user_account_level'),
    ]

    operations = [
    ]
