# Generated by Django 6.0.5 on 2026-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_root_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ai_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
