# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_add_ai_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_level",
            field=models.CharField(
                choices=[("basic", "Basic"), ("silver", "Silver"), ("gold", "Gold")],
                default="basic",
                help_text="Represents the user's account level tier",
                max_length=10,
            ),
        ),
    ]
