# Generated by Django 6.0.5 on 2026-05-29 12:01

from django.db import migrations


class Migration(migrations.Migration):
    """Schema-only / no-op.

    The photo backfill (overriden_photo_url -> custom_photo_image) used to run here
    via synchronous HTTP downloads during `migrate`. That made deploys slow and flaky
    because they depended on a third-party host. The backfill now lives in an
    out-of-band, batched management command:

        python manage.py backfill_user_photos

    `overriden_photo_url` is intentionally kept until that backfill is verified
    complete; a later "contract" migration drops the column.
    """

    dependencies = [
        ("users", "0011_user_custom_photo_image_user_photo_image"),
    ]

    operations = []
