# Generated by Django 6.0.5 on 2026-05-29 12:01

import logging
from urllib.parse import urlparse

import requests
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_photos(apps, schema_editor):
    User = apps.get_model("users", "User")
    UploadedImage = apps.get_model("uploads", "UploadedImage")

    # We must import these directly because apps.get_model doesn't give us the utility
    # and importing in migrations is generally okay for utilities as long as they don't depend on unmigrated models.
    try:
        from uploads.utils import process_uploaded_image, validate_image_source_url
    except ImportError:
        logger.error("Could not import process_uploaded_image, skipping photo migration.")
        return

    max_file_size = 10 * 1024 * 1024
    users = User.objects.filter(overriden_photo_url__isnull=False).exclude(overriden_photo_url="")

    for user in users:
        # Migrate overriden_photo_url -> custom_photo_image
        if user.overriden_photo_url:
            try:
                validate_image_source_url(user.overriden_photo_url)
            except Exception:
                logger.warning("Skipping invalid photo URL for user %s: %s", user.id, urlparse(user.overriden_photo_url).hostname)
                continue

            try:
                with requests.get(user.overriden_photo_url, timeout=5, stream=True, allow_redirects=False) as response:
                    response.raise_for_status()
                    if response.status_code == 200:
                        content_length = response.headers.get("Content-Length")
                        if content_length:
                            try:
                                content_length_value = int(content_length)
                            except ValueError:
                                content_length_value = None
                            if content_length_value and content_length_value > max_file_size:
                                raise ValueError("Custom photo exceeds max file size")

                        content = bytearray()
                        for chunk in response.iter_content(chunk_size=8192):
                            if not chunk:
                                continue
                            content.extend(chunk)
                            if len(content) > max_file_size:
                                raise ValueError("Custom photo exceeds max file size")

                        file_name = user.overriden_photo_url.split("/")[-1] or "custom_photo.jpg"
                        if not file_name.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".webp")):
                            file_name += ".jpg"

                        uploaded_file = SimpleUploadedFile(
                            name=file_name,
                            content=bytes(content),
                            content_type=response.headers.get("Content-Type", "image/jpeg"),
                        )
                        processed_file, width, height, content_type = process_uploaded_image(uploaded_file)

                        img = UploadedImage.objects.create(
                            image=processed_file,
                            original_filename=file_name,
                            content_type=content_type,
                            file_size=processed_file.size,
                            width=width,
                            height=height,
                            uploaded_by_id=user.id,
                        )
                        user.custom_photo_image_id = img.id
            except Exception as e:
                logger.warning("Failed to migrate custom photo for user %s", user.id)

        if user.photo_image_id or user.custom_photo_image_id:
            user.save(update_fields=["photo_image_id", "custom_photo_image_id"])


def reverse_migrate_photos(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_custom_photo_image_user_photo_image"),
    ]

    operations = [
        migrations.RunPython(migrate_photos, reverse_migrate_photos),
    ]
