# Generated by Django 6.0.5 on 2026-05-29 12:01

import logging

import requests
from django.core.files.uploadedfile import SimpleUploadedFile
from django.db import migrations

logger = logging.getLogger(__name__)


def migrate_photos(apps, schema_editor):
    User = apps.get_model("users", "User")
    UploadedImage = apps.get_model("uploads", "UploadedImage")

    # We must import this directly because apps.get_model doesn't give us the utility
    # and importing in migrations is generally okay for utilities as long as they don't depend on unmigrated models.
    try:
        from uploads.utils import process_uploaded_image
    except ImportError:
        logger.error("Could not import process_uploaded_image, skipping photo migration.")
        return

    from django.db.models import Q

    users = User.objects.filter(Q(photo_url__isnull=False) | Q(overriden_photo_url__isnull=False))

    for user in users:
        # Migrate overriden_photo_url -> custom_photo_image
        if user.overriden_photo_url:
            try:
                response = requests.get(user.overriden_photo_url, timeout=5)
                if response.status_code == 200:
                    file_name = user.overriden_photo_url.split("/")[-1] or "custom_photo.jpg"
                    if not file_name.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".webp")):
                        file_name += ".jpg"

                    uploaded_file = SimpleUploadedFile(
                        name=file_name,
                        content=response.content,
                        content_type=response.headers.get("Content-Type", "image/jpeg"),
                    )
                    processed_file, width, height, content_type = process_uploaded_image(uploaded_file)

                    img = UploadedImage.objects.create(
                        image=processed_file,
                        original_filename=file_name,
                        content_type=content_type,
                        file_size=processed_file.size,
                        width=width,
                        height=height,
                        uploaded_by_id=user.id,
                    )
                    user.custom_photo_image_id = img.id
            except Exception as e:
                logger.warning(f"Failed to migrate custom photo for user {user.id}: {e}")

        # Migrate photo_url -> photo_image
        if user.photo_url:
            try:
                # Replace svg with png for dicebear avatars
                url = user.photo_url
                if "dicebear.com" in url and "/svg" in url:
                    url = url.replace("/svg", "/png")

                response = requests.get(url, timeout=5)
                if response.status_code == 200:
                    file_name = url.split("/")[-1] or "photo.jpg"
                    if "?" in file_name:
                        file_name = file_name.split("?")[0]
                    if not file_name.lower().endswith((".jpg", ".jpeg", ".png", ".gif", ".webp")):
                        file_name += ".png" if "dicebear.com" in url else ".jpg"

                    uploaded_file = SimpleUploadedFile(
                        name=file_name,
                        content=response.content,
                        content_type=response.headers.get("Content-Type", "image/jpeg"),
                    )
                    processed_file, width, height, content_type = process_uploaded_image(uploaded_file)

                    img = UploadedImage.objects.create(
                        image=processed_file,
                        original_filename=file_name,
                        content_type=content_type,
                        file_size=processed_file.size,
                        width=width,
                        height=height,
                        uploaded_by_id=user.id,
                    )
                    user.photo_image_id = img.id
            except Exception as e:
                logger.warning(f"Failed to migrate USOS/DiceBear photo for user {user.id}: {e}")

        if user.photo_image_id or user.custom_photo_image_id:
            user.save(update_fields=["photo_image_id", "custom_photo_image_id"])


def reverse_migrate_photos(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_custom_photo_image_user_photo_image"),
    ]

    operations = [
        migrations.RunPython(migrate_photos, reverse_migrate_photos),
    ]
