# Generated by Django 6.0.6 on 2026-06-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_silver_account_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="default_ai_model",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
