# Generated by Django 6.0.5 on 2026-05-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_migrate_user_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='overriden_photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
    ]
