# Generated by Django 6.0.5 on 2026-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_silver_account_level'),
        ('users', '0013_remove_user_overriden_photo_url_and_more'),
    ]

    operations = [
    ]
