# Generated by Django 6.0.6 on 2026-08-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_seed_ai_configuration"),
        ("users", "0013_courseclasstype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="default_ai_model",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_user_settings",
                to="ai.aimodel",
            ),
        ),
    ]
