# Generated by Django 6.0.6 on 2026-06-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersettings_default_ai_model'),
        ('users', '0014_merge_20260529_1625'),
    ]

    operations = [
    ]
