# Generated by Django 6.0.6 on 2026-08-30 11:38

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quizzes", "0033_alter_answerrecord_answered_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "model",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("xai", "xAI"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "minimum_account_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="basic",
                        max_length=10,
                    ),
                ),
                (
                    "input_weight",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "output_weight",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cached_weight",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "AI models",
                "ordering": ("provider", "model"),
            },
        ),
        migrations.CreateModel(
            name="AIAccountLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("email", "Email"),
                            ("student", "Confirmed Student"),
                            ("lecturer", "Lecturer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "account_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "credits_session",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "credits_weekly",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("account_type", "account_level"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_type", "account_level"),
                        name="unique_ai_account_limit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("explain", "Explanation"),
                            ("hint", "Hint"),
                            ("quiz_generation", "Quiz generation"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="chat",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_chat_conversations",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
                "permissions": [
                    ("view_ai_usage_stats", "Can view AI usage statistics"),
                    ("manage_ai_limits", "Can manage AI limits"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limits_enabled", models.BooleanField(default=False)),
                (
                    "grace_buffer_credits",
                    models.DecimalField(
                        decimal_places=4,
                        default=2000,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("staff_bypass_limits", models.BooleanField(default=True)),
                ("fallback_throttle_seconds", models.PositiveIntegerField(default=15)),
                (
                    "fallback_max_output_tokens",
                    models.PositiveIntegerField(
                        default=500,
                        validators=[django.core.validators.MinValueValidator(16)],
                    ),
                ),
                ("limits_reset_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="default_for_settings",
                        to="ai_usage.aimodel",
                    ),
                ),
                (
                    "fallback_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for_settings",
                        to="ai_usage.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI usage settings",
            },
        ),
        migrations.CreateModel(
            name="AIUserLimitOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_session",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "credits_weekly",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_limit_override",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIFallbackGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_fallback_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fallback_grants",
                        to="ai_usage.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at",),
                "indexes": [models.Index(fields=["user", "issued_at"], name="ai_fallback_grant_user_idx")],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=100)),
                ("role", models.CharField(max_length=20)),
                ("content", models.JSONField(default=list)),
                ("order", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_usage.aichatconversation",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chat_messages",
                        to="ai_usage.aimodel",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "order"),
                        name="unique_ai_chat_message_order",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageDailyAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("explain", "Explanation"),
                            ("hint", "Hint"),
                            ("quiz_generation", "Quiz generation"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("cached_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "credits",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("event_count", models.PositiveBigIntegerField(default=0)),
                ("aborted_count", models.PositiveBigIntegerField(default=0)),
                ("error_count", models.PositiveBigIntegerField(default=0)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_aggregates",
                        to="ai_usage.aimodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_daily_aggregates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["date"], name="ai_daily_date_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "scope", "model"),
                        name="unique_ai_daily_aggregate",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("explain", "Explanation"),
                            ("hint", "Hint"),
                            ("quiz_generation", "Quiz generation"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=40,
                    ),
                ),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("cached_tokens", models.PositiveBigIntegerField(default=0)),
                ("credits", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "request_id",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("aborted", models.BooleanField(default=False)),
                (
                    "finish_reason",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("latency_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("quota_exempt", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="ai_usage.aichatconversation",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_events",
                        to="ai_usage.aimodel",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to="quizzes.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="ai_usage_user_created_idx"),
                    models.Index(fields=["created_at"], name="ai_usage_created_idx"),
                    models.Index(
                        fields=["scope", "created_at"],
                        name="ai_usage_scope_created_idx",
                    ),
                    models.Index(
                        fields=["model", "created_at"],
                        name="ai_usage_model_created_idx",
                    ),
                    models.Index(
                        fields=["user", "quota_exempt", "created_at"],
                        name="ai_usage_quota_window_idx",
                    ),
                ],
            },
        ),
    ]
