# Generated by Django 6.0.6 on 2026-07-01 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0013_courseclasstype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WrappedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_global", models.BooleanField(db_index=True, default=False)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("composite_score", models.FloatField(default=0.0)),
                (
                    "percentile",
                    models.FloatField(
                        default=0.0, help_text="Fraction of users this user beat (0–1)."
                    ),
                ),
                ("study_minutes", models.PositiveIntegerField(default=0)),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("active_days", models.PositiveIntegerField(default=0)),
                ("total_answers", models.PositiveIntegerField(default=0)),
                ("answers_per_session", models.PositiveIntegerField(default=0)),
                ("correct", models.PositiveIntegerField(default=0)),
                ("wrong", models.PositiveIntegerField(default=0)),
                ("accuracy_percent", models.PositiveIntegerField(default=0)),
                ("first_attempt_percent", models.PositiveIntegerField(default=0)),
                ("hours", models.JSONField(default=list)),
                ("correct_hours", models.JSONField(default=list)),
                ("peak_hour", models.PositiveIntegerField(default=0)),
                ("top_percent", models.PositiveIntegerField(default=0)),
                ("percentile_fill", models.PositiveIntegerField(default=0)),
                (
                    "hardest_question_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "hardest_quiz_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("hardest_text", models.TextField(blank=True, default="")),
                ("hardest_wrong", models.PositiveIntegerField(blank=True, null=True)),
                ("hardest_correct", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "hardest_image",
                    models.URLField(blank=True, default="", max_length=512),
                ),
                ("creator_people", models.PositiveIntegerField(blank=True, null=True)),
                ("creator_answers", models.PositiveIntegerField(blank=True, null=True)),
                ("creator_hours", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapped_reports",
                        to="users.term",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapped_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="WrappedTopQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Study seconds, for bar scaling."
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_quizzes",
                        to="wrapped.wrappedreport",
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
            },
        ),
        migrations.AddIndex(
            model_name="wrappedreport",
            index=models.Index(
                fields=["user", "term"], name="wrapped_wra_user_id_fcd532_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wrappedreport",
            index=models.Index(
                fields=["term", "is_global"], name="wrapped_wra_term_id_7ef564_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="wrappedreport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_global", True), ("user__isnull", True)),
                    models.Q(("is_global", False), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="wrapped_global_user_consistency",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrappedreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_global", False), ("user__isnull", False)),
                fields=("user", "term"),
                name="one_wrapped_per_user_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="wrappedreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_global", True), ("user__isnull", True)),
                fields=("term",),
                name="one_global_wrapped_per_term",
            ),
        ),
    ]
