"""
Django settings for testownik_core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

import dotenv
from authlib.integrations.django_client import OAuth

logger = logging.getLogger(__name__)

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-mo_va&2*lmj8z2ymm5i##wze&u%#d=v1boeki1tc=7@9sn3ilf")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(",")

# Allow preview environments (e.g. PR builds) for CORS and Redirects
ALLOW_PREVIEW_ENVIRONMENTS = os.getenv("ALLOW_PREVIEW_ENVIRONMENTS", "False") == "True"

PREVIEW_ORIGIN_REGEXES = [
    r"^https://[\w-]+-testownik\.b\.solvro\.pl$",
]

if ALLOW_PREVIEW_ENVIRONMENTS:
    CORS_ALLOWED_ORIGIN_REGEXES = PREVIEW_ORIGIN_REGEXES

CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000").split(",")

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000").rstrip("/")

# Internal API key for server-to-server authentication (e.g., Next.js server-side)
INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY")

_additional_redirect_origins = os.environ.get("ALLOWED_REDIRECT_ORIGINS", "").split(",")
ALLOWED_REDIRECT_ORIGINS = [FRONTEND_URL] + [o.strip().rstrip("/") for o in _additional_redirect_origins if o.strip()]

JWT_COOKIE_SECURE = not DEBUG
JWT_COOKIE_SAMESITE = "Lax"
JWT_COOKIE_DOMAIN = os.getenv("JWT_COOKIE_DOMAIN", None)

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "users.apps.UsersConfig",
    "grades.apps.GradesConfig",
    "quizzes.apps.QuizzesConfig",
    "alerts.apps.AlertsConfig",
    "maintenance.apps.MaintenanceConfig",
    "testownik_core.apps.TestownikCoreConfig",
    "uploads.apps.UploadsConfig",
    "constance",
    "constance.backends.database",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "adrf",
    "drf_spectacular",
    "django_filters",
]

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_CONFIG = {
    "MAINTENANCE_MODE": (False, "Is the site in maintenance mode?"),
}

CONSTANCE_CONFIG_FIELDSETS = {
    "Maintenance Mode": ("MAINTENANCE_MODE",),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "maintenance.middleware.MaintenanceModeMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
}

if os.getenv("JWT_SECRET") is None:
    logger.warning("JWT_SECRET is not set in the environment, fallback to SECRET_KEY")
    logger.warning("This is not recommended for production")

SIMPLE_JWT = {
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "ROTATE_REFRESH_TOKENS": True,
    "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
}

ROOT_URLCONF = "testownik_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "testownik_core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": os.environ.get("DB_USER", "user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "password"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}

AUTH_USER_MODEL = "users.User"
LOGIN_URL = "login_usos"

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHLIB_OAUTH_CLIENTS = {
    "solvro-auth": {
        "client_id": os.getenv("SOLVRO_AUTH_CLIENT_ID", "testownik"),
        "client_secret": os.getenv("SOLVRO_AUTH_CLIENT_SECRET", ""),
        "access_token_url": "https://auth.solvro.pl/realms/solvro/protocol/openid-connect/token",
        "access_token_params": None,
        "refresh_token_url": None,
        "authorize_url": "https://auth.solvro.pl/realms/solvro/protocol/openid-connect/auth",
        "api_base_url": "https://api.testownik.solvro.pl/",
        "server_metadata_url": "https://auth.solvro.pl/realms/solvro/.well-known/openid-configuration",
        "client_kwargs": {"scope": "openid profile email"},
    }
}

oauth = OAuth()
oauth.register(name="solvro-auth")

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "api/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if os.getenv("S3_BUCKET_NAME"):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": os.getenv("S3_ACCESS_KEY_ID"),
                "secret_key": os.getenv("S3_SECRET_ACCESS_KEY"),
                "bucket_name": os.getenv("S3_BUCKET_NAME"),
                "region_name": os.getenv("S3_REGION_NAME", "eu-central-1"),
                "endpoint_url": os.getenv("S3_ENDPOINT_URL"),
                "custom_domain": os.getenv("S3_CUSTOM_DOMAIN"),
                "file_overwrite": False,
                "default_acl": "public-read",
                "querystring_auth": False,
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email settings
EMAIL_HOST = os.getenv("EMAIL_HOST")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
EMAIL_PORT_ENV = os.getenv("EMAIL_PORT")
if EMAIL_PORT_ENV is None:
    EMAIL_PORT = 587
else:
    try:
        EMAIL_PORT = int(EMAIL_PORT_ENV)
    except ValueError:
        logger.warning("Invalid EMAIL_PORT '%s', falling back to default 587", EMAIL_PORT_ENV)
        EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Testownik Solvro <testownik@solvro.pl>")
EMAIL_TIMEOUT = 10

# DRF Spectacular Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Testownik API",
    "DESCRIPTION": "API documentation for Testownik application",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
    "SERVE_PUBLIC": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}

TASKS = {"default": {"BACKEND": "django.tasks.backends.immediate.ImmediateBackend"}}
