# Generated by Django 5.2 on 2025-05-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Maintenance mode',
                'verbose_name_plural': 'Maintenance mode',
            },
        ),
    ]
