# Generated by Django 5.2 on 2025-05-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancemode',
            options={'verbose_name': 'Maintenance mode', 'verbose_name_plural': 'Maintenance mode'},
        ),
    ]
