# Generated by Django 5.0.7 on 2024-08-29 12:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Każdy zalogowany użytkownik będzie mógł zobaczyć tę bazę",
                    ),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Każdy, nawet niezalogowany użytkownik będzie mógł wyświetlić tę bazę wchodząc na link",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Nie będzie wyświetlany autor testu, cały czas będzie można zgłosić błąd w pytaniu",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("questions", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="QuizProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_question", models.PositiveIntegerField(default=0)),
                ("mastered_questions", models.JSONField(blank=True, default=list)),
                ("failed_questions", models.JSONField(blank=True, default=list)),
                ("study_time", models.DurationField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SharedQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
