# Generated by Django 5.2 on 2025-06-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedquiz",
            name="allow_edit",
            field=models.BooleanField(default=False),
        ),
    ]
