# Generated by Django 5.1.1 on 2024-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_remove_quiz_is_public_quiz_visibility"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizprogress",
            name="failed_questions",
        ),
        migrations.RemoveField(
            model_name="quizprogress",
            name="mastered_questions",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="correct_answers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="reoccurrences",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="wrong_answers_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
