# Generated by Django 5.1.1 on 2024-09-16 15:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_remove_quizprogress_failed_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizprogress",
            name="study_time",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
