# Generated by Django 6.0 on 2026-01-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_reoccurrences',
            field=models.PositiveIntegerField(default=3, help_text='Maksymalna liczba powtórzeń pytania po błędnej odpowiedzi'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='quizzes.folder'),
        ),
    ]
