# Generated by Django 6.0 on 2026-01-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_folder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='tips',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='quizzes.folder'),
        ),
    ]
