# Generated by Django - data migration for questions JSON to models

from django.db import migrations


def migrate_questions(apps, schema_editor):
    """Migrate questions from JSON field to Question/Answer models."""
    Quiz = apps.get_model("quizzes", "Quiz")
    Question = apps.get_model("quizzes", "Question")
    Answer = apps.get_model("quizzes", "Answer")

    for quiz in Quiz.objects.exclude(questions=[]):
        for idx, q_data in enumerate(quiz.questions):
            question = Question.objects.create(
                quiz=quiz,
                order=q_data.get("id", idx + 1),
                text=q_data.get("question", q_data.get("text", "")),
                image=q_data.get("image"),
                explanation=q_data.get("explanation"),
                multiple=q_data.get("multiple", False),
            )
            for a_idx, a_data in enumerate(q_data.get("answers", [])):
                is_correct = a_data.get("correct", a_data.get("is_correct"))
                if is_correct is None:
                    is_correct = False
                Answer.objects.create(
                    question=question,
                    order=a_idx,
                    text=a_data.get("answer", a_data.get("text", "")),
                    image=a_data.get("image"),
                    is_correct=bool(is_correct),
                )


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert models back to JSON."""
    Quiz = apps.get_model("quizzes", "Quiz")
    Question = apps.get_model("quizzes", "Question")

    for quiz in Quiz.objects.all():
        questions_json = []
        for question in Question.objects.filter(quiz=quiz).order_by("order"):
            q_data = {
                "id": question.order,
                "question": question.text,
                "multiple": question.multiple,
                "answers": [
                    {
                        "answer": a.text,
                        "correct": a.is_correct,
                        **({"image": a.image} if a.image else {}),
                    }
                    for a in question.answers.order_by("order")
                ],
            }
            if question.image:
                q_data["image"] = question.image
            if question.explanation:
                q_data["explanation"] = question.explanation
            questions_json.append(q_data)
        quiz.questions = questions_json
        quiz.save()


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0007_question_answer"),
    ]

    operations = [
        migrations.RunPython(migrate_questions, reverse_migration),
    ]
