# Generated by Django 6.0 on 2026-01-15 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_migrate_questions_data"),
    ]

    operations = [
        # First remove the JSON questions field
        migrations.RemoveField(
            model_name="quiz",
            name="questions",
        ),
        # Then rename the related_name from questions_set to questions
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.quiz",
            ),
        ),
    ]
