# Generated by Django - data migration for legacy progress

from django.db import migrations


def migrate_progress(apps, schema_editor):
    """
    Migrate existing QuizProgress records to QuizSession and AnswerRecord.
    Reverse engineers 'reoccurrences' count into synthetic history.
    """
    QuizProgress = apps.get_model("quizzes", "QuizProgress")
    QuizSession = apps.get_model("quizzes", "QuizSession")
    AnswerRecord = apps.get_model("quizzes", "AnswerRecord")
    Question = apps.get_model("quizzes", "Question")
    Answer = apps.get_model("quizzes", "Answer")

    INITIAL_REOCCURRENCES = 1


    for progress in QuizProgress.objects.all():
        session, created = QuizSession.objects.update_or_create(
            quiz=progress.quiz,
            user=progress.user,
            is_active=True,
            defaults={
                "started_at": progress.last_activity,
                "study_time": progress.study_time,
            }
        )
        
        if progress.current_question:
            question = Question.objects.filter(
                quiz=progress.quiz, 
                order=progress.current_question
            ).first()
            if question:
                session.current_question = question
                session.save(update_fields=["current_question"])

        reoccurrences_data = progress.reoccurrences or []
        
        for item in reoccurrences_data:
            # Skip items that aren't dictionaries or have missing/invalid data
            if not isinstance(item, dict):
                continue
            order = item.get("id")
            if order is None:
                continue
            try:
                count = int(item.get("reoccurrences", 0))
            except (TypeError, ValueError):
                continue
            
            question = Question.objects.filter(quiz=progress.quiz, order=order).first()
            if not question:
                continue

            delta = count - INITIAL_REOCCURRENCES
            
            wrong_needed = 0
            correct_needed = 0
            
            if delta == 0:
                pass 
            elif delta < 0:
                correct_needed = 1
            else:
                if delta % 2 == 0:
                    wrong_needed = delta // 2
                else:
                    wrong_needed = (delta + 1) // 2
                    correct_needed = 1

            timestamp = progress.last_activity
            
            for _ in range(wrong_needed):
                AnswerRecord.objects.create(
                    session=session,
                    question=question,
                    selected_answers=[],
                    was_correct=False,
                    answered_at=timestamp
                )
            
            if correct_needed > 0:
                correct_ans = Answer.objects.filter(question=question, is_correct=True).first()
                selected = [str(correct_ans.id)] if correct_ans else []
                
                for _ in range(correct_needed):
                    AnswerRecord.objects.create(
                        session=session,
                        question=question,
                        selected_answers=selected,
                        was_correct=True,
                        answered_at=timestamp
                    )


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0010_quizsession_answerrecord_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_progress, migrations.RunPython.noop),
    ]
