# Generated by Django 6.0 on 2026-01-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0011_migrate_legacy_progress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique_answer_order_per_question",
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_order_per_quiz",
        ),
    ]
