# Generated by Django 6.0 on 2026-01-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
