# Generated by Django 6.0.1 on 2026-01-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('ARCHIVE', 'Archive'), ('REGULAR', 'Regular')], default='REGULAR', max_length=10),
        ),
    ]
