# Generated by Django 6.0 on 2026-01-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0012_alter_folder_options_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="image",
            new_name="image_url",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="image",
            new_name="image_url",
        ),
    ]
