# Generated by Django 6.0.1 on 2026-01-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='skipped_due_to_limit',
            field=models.BooleanField(default=False),
        ),
    ]
