# Generated by Django 6.0.1 on 2026-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_question_repetitions',
            field=models.PositiveIntegerField(default=3, help_text='Maksymalna liczba powtórzeń tego samego pytania w jednej sesji'),
        ),
    ]
