# Generated by Django 6.0 on 2026-01-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
