# Generated by Django 6.0 on 2026-01-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_max_reoccurrences_alter_folder_parent'),
        ('quizzes', '0012_alter_folder_options_alter_quiz_options_and_more'),
    ]

    operations = [
    ]
