# Generated by Django 5.2.7 on 2026-01-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_rename_image_to_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerrecord',
            name='skipped_due_to_limit',
            field=models.BooleanField(default=False),
        ),
    ]
