# Generated by Django 6.0.1 on 2026-01-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0013_rename_image_to_image_url"),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="uploads.uploadedimage",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="image_upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="uploads.uploadedimage",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
