# Generated by Django 6.0.1 on 2026-01-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_folder_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='type',
            new_name='folder_type',
        ),
    ]
