# Generated by Django 6.0 on 2026-01-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_merge_20260120_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='max_reoccurrences',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_question_repetitions',
            field=models.PositiveIntegerField(default=3, help_text='Maksymalna liczba powtórzeń tego samego pytania w jednej sesji'),
        ),
    ]
