# Generated by Django 6.0 on 2026-02-07 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0014_rename_type_folder_folder_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('archive', 'Archive'), ('regular', 'Regular')], default='regular', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('folder_type', 'archive')), fields=('owner', 'folder_type'), name='unique_archive_per_user'),
        ),
    ]
