# Generated by Django 6.0.1 on 2026-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0014_answer_image_upload_question_image_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
