# Generated by Django 6.0.1 on 2026-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0015_alter_answer_text_alter_question_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
