# Generated by Django 6.0.2 on 2026-02-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0017_merge_20260207_1401"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
            },
        ),
    ]
