# Generated by Django 6.0.1 on 2026-02-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0015_alter_folder_folder_type_and_more'),
        ('quizzes', '0016_quizsession_updated_at'),
    ]

    operations = [
    ]
