# Generated by Django 6.0.2 on 2026-02-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0017_alter_quiz_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuizProgress",
        ),
    ]
