# Generated by Django 6.0.2 on 2026-02-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_sharedfolder'),
        ('quizzes', '0018_delete_quizprogress'),
    ]

    operations = [
    ]
