# Generated by Django 6.0.1 on 2026-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_questionissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Zamknięte'), (1, 'Otwarte'), (2, 'Prawda/Fałsz')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='tf_answer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
