# Generated by Django 6.0.1 on 2026-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0020_question_question_type_question_tf_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_flashcard',
            field=models.BooleanField(default=False),
        ),
    ]
