# Generated by Django 6.0.2 on 2026-03-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0019_questionissue'),
        ('quizzes', '0021_create_root_folders'),
    ]

    operations = [
    ]
