# Generated by Django 6.0.3 on 2026-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_question_is_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_markdown_enabled',
            field=models.BooleanField(default=True, help_text='Określa, czy tekst pytania ma wspierać formatowanie Markdown'),
        ),
    ]
