# Generated by Django 6.0.2 on 2026-03-08 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0021_question_is_flashcard'),
        ('quizzes', '0022_merge_0019_questionissue_0021_create_root_folders'),
    ]

    operations = [
    ]
