# Generated by Django 6.0.1 on 2026-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_merge_20260207_1401'),
        ('quizzes', '0022_merge_0019_questionissue_0021_create_root_folders'),
    ]

    operations = [
    ]
