# Generated by Django 6.0.1 on 2026-04-02 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0023_folder_architecture'),
        ('users', '0009_user_root_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sharedfolder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('study_group__isnull', True), ('user__isnull', False)), models.Q(('study_group__isnull', False), ('user__isnull', True)), _connector='OR'), name='sharedfolder_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='sharedfolder',
            constraint=models.UniqueConstraint(fields=('folder', 'user'), name='unique_sharedfolder_folder_user'),
        ),
        migrations.AddConstraint(
            model_name='sharedfolder',
            constraint=models.UniqueConstraint(fields=('folder', 'study_group'), name='unique_sharedfolder_folder_study_group'),
        ),
    ]
