# Generated by Django 6.0.1 on 2026-04-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0022_comment_quizrating'),
        ('quizzes', '0025_folder_architecture_alter_folder_fields'),
    ]

    operations = [
    ]
