# Generated by Django 6.0.2 on 2026-04-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0017_merge_20260207_1401'),
        ('quizzes', '0025_folder_architecture_alter_folder_fields'),
    ]

    operations = [
    ]
