# Generated by Django 6.0.4 on 2026-04-20 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0026_comment_quizrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="folder_type",
            field=models.CharField(
                choices=[("archive", "Archive"), ("regular", "Regular")],
                default="regular",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("folder_type", "archive")),
                fields=("owner", "folder_type"),
                name="unique_archive_per_user",
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
