# Generated by Django 6.0.2 on 2026-05-08 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0028_backfill_archive_folders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('archive', 'Archive'), ('regular', 'Regular'), ('shared_drive', 'Shared Drive')], default='regular', max_length=12),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SharedDriveMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('quiz_manager', 'Quiz Manager'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='viewer', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_drive_users', to='quizzes.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_drive_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('drive', 'user'), name='unique_shared_drive_user')],
            },
        ),
    ]
