# Generated by Django 6.0.4 on 2026-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0028_backfill_archive_folders"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answerrecord",
            index=models.Index(
                fields=["session", "question", "answered_at"],
                name="answerrec_session_q_at_idx",
            ),
        ),
    ]
