# Generated by Django 6.0.5 on 2026-05-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0029_answerrecord_answerrec_session_q_at_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_ai_generated",
            field=models.BooleanField(default=False),
        ),
    ]
