# Generated by Django 6.0.5 on 2026-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0030_add_ai_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_ai_generated",
            field=models.BooleanField(
                default=False,
                help_text="Cała baza została wygenerowana przez AI (np. przez asystenta MCP)",
            ),
        ),
    ]
