# Generated by Django 6.0.6 on 2026-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0032_add_trash_folder_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerrecord",
            name="answered_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="quizsession",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
