# Generated by Django 6.1 on 2026-09-06 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_seed_ai_configuration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={
                "ordering": ("order", "provider", "model"),
                "verbose_name_plural": "AI models",
            },
        ),
        migrations.RenameField(
            model_name="aimodel",
            old_name="cached_weight",
            new_name="cache_read_weight",
        ),
        migrations.RenameField(
            model_name="aiusagedailyaggregate",
            old_name="cached_tokens",
            new_name="cache_read_tokens",
        ),
        migrations.RenameField(
            model_name="aiusageevent",
            old_name="cached_tokens",
            new_name="cache_read_tokens",
        ),
        migrations.AddField(
            model_name="aimodel",
            name="cache_write_weight",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="aimodel",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusagedailyaggregate",
            name="cache_write_tokens",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aiusageevent",
            name="cache_write_tokens",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
