# Generated by Django 6.0.5 on 2026-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('in_app', 'In App'), ('push', 'Push')], max_length=20),
        ),
    ]
